// Mirrors the permission codes seeded in db/init/02_seed.sql — keep in sync.
export const PERMISSIONS = {
  CLIENTS_READ: "clients.read",
  CLIENTS_CREATE: "clients.create",
  CLIENTS_UPDATE: "clients.update",
  CLIENTS_DELETE: "clients.delete",
  PROVIDERS_READ: "providers.read",
  PROVIDERS_CREATE: "providers.create",
  PROVIDERS_UPDATE: "providers.update",
  PROVIDERS_DELETE: "providers.delete",
  RATE_SETS_READ: "rate_sets.read",
  RATE_SETS_CREATE: "rate_sets.create",
  RATE_SETS_UPDATE: "rate_sets.update",
  RATE_SETS_DELETE: "rate_sets.delete",
  RATE_SETS_IMPORT: "rate_sets.import",
  INVOICES_READ: "invoices.read",
  INVOICES_CREATE: "invoices.create",
  INVOICES_UPDATE: "invoices.update",
  INVOICES_DELETE: "invoices.delete",
  INVOICES_UPLOADS_MANAGE: "invoices.uploads.manage",
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DELETE: "users.delete",
  USER_ROLES_READ: "user_roles.read",
  USER_ROLES_CREATE: "user_roles.create",
  USER_ROLES_UPDATE: "user_roles.update",
  USER_ROLES_DELETE: "user_roles.delete",
  GENDERS_READ: "genders.read",
  GENDERS_CREATE: "genders.create",
  GENDERS_UPDATE: "genders.update",
  GENDERS_DELETE: "genders.delete",
  AUTH_SESSIONS_READ: "auth_sessions.read",
  AUTH_SESSIONS_REVOKE: "auth_sessions.revoke",
  AUTH_SESSIONS_DELETE: "auth_sessions.delete",
  AUDIT_LOGS_READ: "audit_logs.read",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
